# Generated by Django 4.2.26 on 2025-12-10 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('subscription', models.CharField(choices=[('free', 'Любитель'), ('premium', 'Конник'), ('pro', 'Спортсмен')], default='free', max_length=20)),
                ('subscription_active', models.BooleanField(default=False)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя лошади')),
                ('breed', models.CharField(choices=[('ahaltekin', 'Ахалтекинская'), ('arab', 'Арабская'), ('orlov', 'Орловский рысак'), ('trakenen', 'Тракененская'), ('budyonny', 'Будённовская'), ('don', 'Донская'), ('tinker', 'Цыганская (тинкер)'), ('other', 'Другая порода')], max_length=50, verbose_name='Порода')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст (лет)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Масть')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лошадь',
                'verbose_name_plural': 'Лошади',
                'ordering': ['name'],
            },
        ),
    ]
