# Generated by Django 4.2.26 on 2025-12-10 21:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя лошади')),
                ('breed', models.CharField(choices=[('arabian', 'Арабская скаковая'), ('orlov', 'Орловский рысак'), ('trakehner', 'Тракененская'), ('don', 'Донская'), ('budyonny', 'Будённовская')], max_length=50, verbose_name='Порода')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст (лет)')),
                ('color', models.CharField(max_length=50, verbose_name='Масть')),
                ('level', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], max_length=20, verbose_name='Уровень подготовки')),
                ('base_price_hour', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10, verbose_name='Базовая цена за час')),
                ('premium_price_hour', models.DecimalField(decimal_places=2, default=Decimal('1700.00'), max_digits=10, verbose_name='Цена за час для Premium')),
                ('pro_price_hour', models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10, verbose_name='Цена за час для Pro')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна для брони')),
                ('image', models.ImageField(blank=True, null=True, upload_to='horses/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Лошадь',
                'verbose_name_plural': 'Лошади',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HorseBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('booking_time', models.TimeField(verbose_name='Время бронирования')),
                ('duration_hours', models.PositiveIntegerField(default=1, verbose_name='Длительность (часы)')),
                ('base_price_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена за час')),
                ('user_price_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена для пользователя за час')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка %')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('client_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('client_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='horses.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронирование лошади',
                'verbose_name_plural': 'Бронирования лошадей',
                'ordering': ['-booking_date', 'booking_time'],
            },
        ),
    ]
