# Generated by Django 4.2.26 on 2025-12-10 12:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='🥕', max_length=50, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория корма',
                'verbose_name_plural': 'Категории кормов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Новый товар', max_length=200, verbose_name='Название')),
                ('description', models.TextField(default='Описание товара', verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, verbose_name='Базовая цена')),
                ('premium_price', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=10, verbose_name='Цена для Premium')),
                ('pro_price', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=10, verbose_name='Цена для Pro')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('piece', 'шт.'), ('pack', 'упак.'), ('liter', 'л'), ('bag', 'мешок')], default='kg', max_length=10, verbose_name='Единица измерения')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Вес/объем')),
                ('calories', models.IntegerField(default=0, verbose_name='Ккал на 100г')),
                ('protein', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Белки %')),
                ('fat', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Жиры %')),
                ('fiber', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Клетчатка %')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/', verbose_name='Изображение')),
                ('stock', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('min_order', models.IntegerField(default=1, verbose_name='Минимальный заказ')),
                ('max_order', models.IntegerField(default=100, verbose_name='Максимальный заказ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('is_best_seller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новинка')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, verbose_name='Рейтинг')),
                ('review_count', models.IntegerField(default=0, verbose_name='Количество отзывов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='food.foodcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Оценка')),
                ('comment', models.TextField(default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food.fooditem', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('food', 'user')},
            },
        ),
    ]
