# Generated by Django 4.2.26 on 2025-12-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='calcium_percent',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=5, verbose_name='Кальций (%)'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='composition',
            field=models.TextField(default='Овёс очищенный 100%', verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='expiration_months',
            field=models.IntegerField(default=12, verbose_name='Срок годности (месяцев)'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='fat_percent',
            field=models.DecimalField(decimal_places=2, default=4.0, max_digits=5, verbose_name='Жиры (%)'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='fiber_percent',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Клетчатка (%)'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='manufacturer',
            field=models.CharField(default='ООО "Конный корм"', max_length=200, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='phosphorus_percent',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=5, verbose_name='Фосфор (%)'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='production_location',
            field=models.CharField(default='г. Москва', max_length=300, verbose_name='Место производства'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='protein_percent',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=5, verbose_name='Протеин (%)'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='quality_certificates',
            field=models.CharField(default='ГОСТ', max_length=300, verbose_name='Сертификаты качества'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='recommendations',
            field=models.TextField(default='Давать согласно рекомендациям ветеринара', verbose_name='Рекомендации по кормлению'),
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='storage_conditions',
            field=models.TextField(default='В сухом помещении', verbose_name='Условия хранения'),
        ),
    ]
