# Generated by Django 4.2.26 on 2025-12-11 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_foodcategory_calcium_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breed', models.CharField(choices=[('arabian', 'Арабская скаковая'), ('orlov', 'Орловский рысак'), ('trakehner', 'Тракененская'), ('don', 'Донская'), ('budyonny', 'Будённовская'), ('friesian', 'Фризская'), ('hannover', 'Ганноверская'), ('akhalteke', 'Ахалтекинская')], max_length=50, verbose_name='Порода')),
                ('age', models.IntegerField(verbose_name='Возраст (лет)')),
                ('weight', models.IntegerField(verbose_name='Вес (кг)')),
                ('purpose', models.CharField(choices=[('sport', 'Спорт'), ('walk', 'Прогулки'), ('foal', 'Выращивание жеребёнка'), ('rehabilitation', 'Реабилитация'), ('breeding', 'Племенное разведение'), ('show', 'Выставки')], max_length=50, verbose_name='Цель содержания')),
                ('budget', models.CharField(choices=[('economy', 'Экономный'), ('standard', 'Стандартный'), ('premium', 'Премиум'), ('professional', 'Профессиональный')], max_length=20, verbose_name='Бюджет')),
                ('activity_level', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], max_length=20, verbose_name='Уровень активности')),
                ('food_type', models.CharField(max_length=200, verbose_name='Тип корма')),
                ('daily_norm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Суточная норма (кг)')),
                ('feeding_frequency', models.IntegerField(verbose_name='Частота кормления (раз/день)')),
                ('next_purchase_date', models.DateField(verbose_name='Дата следующей закупки')),
                ('next_vet_check', models.DateField(verbose_name='Дата следующего ветосмотра')),
                ('recommended_products', models.JSONField(default=list, verbose_name='Рекомендованные товары')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные рекомендации')),
                ('total_monthly_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая месячная стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Рекомендация ИИ',
                'verbose_name_plural': 'Рекомендации ИИ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horse_name', models.CharField(max_length=100, verbose_name='Кличка лошади')),
                ('horse_breed', models.CharField(max_length=50, verbose_name='Порода')),
                ('horse_age', models.IntegerField(verbose_name='Возраст')),
                ('horse_weight', models.IntegerField(verbose_name='Вес (кг)')),
                ('products_added_to_cart', models.IntegerField(default=0, verbose_name='Товаров добавлено в корзину')),
                ('is_followed', models.BooleanField(default=False, verbose_name='Следовал рекомендациям')),
                ('consulted_at', models.DateTimeField(auto_now_add=True)),
                ('last_reminder', models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.recommendation', verbose_name='Рекомендация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История консультаций',
                'verbose_name_plural': 'История консультаций',
                'ordering': ['-consulted_at'],
            },
        ),
    ]
