# Generated by Django 4.2.26 on 2025-12-11 00:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_recommendation_consultationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationhistory',
            name='horse_age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='consultationhistory',
            name='horse_breed',
            field=models.CharField(default='other', max_length=50, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='consultationhistory',
            name='horse_name',
            field=models.CharField(default='Не указано', max_length=100, verbose_name='Кличка лошади'),
        ),
        migrations.AlterField(
            model_name='consultationhistory',
            name='horse_weight',
            field=models.IntegerField(default=0, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='breed',
            field=models.CharField(choices=[('arabian', 'Арабская скаковая'), ('orlov', 'Орловский рысак'), ('trakehner', 'Тракененская'), ('don', 'Донская'), ('budyonny', 'Будённовская'), ('friesian', 'Фризская'), ('hannover', 'Ганноверская'), ('akhalteke', 'Ахалтекинская'), ('other', 'Другая')], max_length=50, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='daily_norm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Суточная норма (кг)'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='feeding_frequency',
            field=models.IntegerField(default=3, verbose_name='Частота кормления (раз/день)'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='food_type',
            field=models.CharField(default='Сбалансированный корм', max_length=200, verbose_name='Тип корма'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='next_purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей закупки'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='next_vet_check',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего ветосмотра'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительные рекомендации'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='total_monthly_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Общая месячная стоимость'),
        ),
        migrations.CreateModel(
            name='AIChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Консультация', max_length=200, verbose_name='Название сессии')),
                ('horse_data', models.JSONField(default=dict, verbose_name='Данные о лошади')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия чата с ИИ',
                'verbose_name_plural': 'Сессии чата с ИИ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system', 'Система'), ('user', 'Пользователь'), ('assistant', 'ИИ')], max_length=20, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='food.aichatsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['created_at'],
            },
        ),
    ]
