# Generated by Django 4.2.26 on 2025-12-10 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина покупок',
                'verbose_name_plural': 'Корзины покупок',
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('customer_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Город')),
                ('delivery_street', models.CharField(max_length=200, verbose_name='Улица')),
                ('delivery_house', models.CharField(max_length=20, verbose_name='Дом')),
                ('delivery_apartment', models.CharField(blank=True, max_length=20, verbose_name='Квартира')),
                ('delivery_index', models.CharField(blank=True, max_length=10, verbose_name='Индекс')),
                ('delivery_method', models.CharField(choices=[('courier', 'Курьерская доставка'), ('pickup', 'Самовывоз'), ('post', 'Почта России')], default='courier', max_length=20, verbose_name='Способ доставки')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('sbp', 'СБП'), ('applepay', 'Apple Pay'), ('googlepay', 'Google Pay'), ('cash', 'Наличные при получении')], default='card', max_length=20, verbose_name='Способ оплаты')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма товаров')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки')),
                ('assembly_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость сборки')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('confirmed', 'Подтвержден'), ('in_progress', 'В работе'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('promo_code', models.CharField(blank=True, max_length=50, verbose_name='Промокод')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('subscription_applied', models.CharField(blank=True, max_length=20, verbose_name='Примененная подписка')),
                ('subscription_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Экономия по подписке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ кормов',
                'verbose_name_plural': 'Заказы кормов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.fooditem', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.foodorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Элемент заказа кормов',
                'verbose_name_plural': 'Элементы заказа кормов',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_at_addition', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена при добавлении')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Корзина')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.fooditem', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
                'unique_together': {('cart', 'food')},
            },
        ),
    ]
